name: rpi-backlight
base: core18
version: '1.1.3'
license: MIT
summary: Backlight switch for Raspberry Pi
description: |
  RPI-Backlight is a very small tool written as bash script to switch the backlight on and off.
  It includes a timer to turn the lights off at 11pm and on at 06am. These parameters are fixed.

  The tool is build for a Raspberry Pi 3 setup running Ubuntu Core. Now it is based on Core18.

  If you like to contribute, please visit my Github repository. 

icon: snap/gui/logo.png

grade: devel #[stable or devel]
confinement: devmode #[strict or devmode]

architectures:
  - build-on: [armhf, arm64]
    run-on: [armhf, arm64]

apps:
  backlight:
    command: sh $SNAP/opt/backlight/bin/backlight.sh
    daemon: oneshot
    timer: 00:00-24:00/12

parts:
  backlight:
    plugin: dump
    source: snap/local/scripts
    source-type: local
    organize:
      backlight.sh: opt/backlight/bin/backlight.sh
  