name: rpi-backlight
base: core20
type: app
version: '0.0.1'
summary: A backlight timer for the Raspberry Pi.
description: |
  A backlight timer for the Raspberry Pi.
grade: devel
confinement: devmode

apps:
  rpi-backlight-off:
    command: bin/rpi_backlight_off.sh
    daemon: simple
    restart-condition: always
    timer: "23:00-06:00/96"
  rpi-backlight-on:
    command: bin/rpi_backlight_on.sh
    daemon: simple
    restart-condition: always
    timer: "06:00-23:00/96"

parts:
  rpi-backlight-off:
    plugin: copy
    files:
      rpi_backlight_off.sh: bin/
  rpi-backlight-on:
    plugin: copy
    files:
      rpi_backlight_on.sh: bin/