name: rpi-backlight
base: core18
version: '1.0.0'
summary: Backlight switch for Raspberry Pi
description: |
  RPI-Backlight is a very small tool written as bash script to switch the backlight on and off.
  It includes a timer to turn the lights off at 11pm and on at 06am. These parameters are fixed.

  The tool is build for a Raspberry Pi 3 setup running Ubuntu Core. Now it is based on Core18.

  If you like to contribute, please visit my Github repository. 

grade: stable
confinement: strict
architectures:
  - build-on: [armhf, arm64]
    run-on: [armhf, arm64]

apps:
  rpi-backlight-off:
    command: sh $SNAP/opt/rpi-backlight-off/bin/rpi-backlight-off.sh
    daemon: simple
    restart-condition: always
    timer: "23:00-06:00/96"
  rpi-backlight-on:
    command: sh $SNAP/opt/rpi-backlight-on/bin/rpi-backlight-on.sh
    daemon: simple
    restart-condition: always
    timer: "06:00-23:00/96"

parts:
  rpi-backlight-off:
    plugin: dump
    source: snap/local/scripts
    source-type: local
    organize:
      rpi-backlight-off.sh: opt/rpi-backlight-off/bin/rpi-backlight-off.sh
  rpi-backlight-on:
    plugin: dump
    source: snap/local/scripts
    source-type: local
    organize:
      rpi-backlight-on.sh: opt/rpi-backlight-on/bin/rpi-backlight-on.sh
  