name: rpi-backlight
base: core18
version: '1.1.0'
license: MIT
summary: Backlight switch for Raspberry Pi
description: |
  RPI-Backlight is a very small tool written as bash script to switch the backlight on and off.
  It includes a timer to turn the lights off at 11pm and on at 06am. These parameters are fixed.

  The tool is build for a Raspberry Pi 3 setup running Ubuntu Core. Now it is based on Core18.

  If you like to contribute, please visit my Github repository. 

icon: snap/gui/logo.png
grade: stable
confinement: strict
architectures:
  - build-on: [armhf, arm64]
    run-on: [armhf, arm64]

apps:
  backlight-off:
    command: sh $SNAP/opt/backlight-off/bin/backlight-off.sh
    daemon: oneshot
    timer: 23:00-05:59/12
  backlight-on:
    command: sh $SNAP/opt/backlight-on/bin/backlight-on.sh
    daemon: oneshot
    timer: 06:00-22:59/12

parts:
  backlight-off:
    plugin: dump
    source: snap/local/scripts
    source-type: local
    organize:
      backlight-off.sh: opt/backlight-off/bin/backlight-off.sh
  backlight-on:
    plugin: dump
    source: snap/local/scripts
    source-type: local
    organize:
      backlight-on.sh: opt/backlight-on/bin/backlight-on.sh
  