name: rpi-backlight
base: core18
version: '0.1'
summary: A backlight timer for the Raspberry Pi.
description: |
  A backlight timer for the Raspberry Pi.
grade: devel
confinement: devmode
architectures:
  - build-on: [armhf, arm64]
    run-on: [armhf, arm64]

apps:
  rpi-backlight-off:
    command: sh $SNAP/opt/rpi-backlight-off/bin/rpi-backlight-off.sh
    daemon: simple
    restart-condition: always
    timer: "23:00-06:00/96"
  rpi-backlight-on:
    command: sh $SNAP/opt/rpi-backlight-on/bin/rpi-backlight-on.sh
    daemon: simple
    restart-condition: always
    timer: "06:00-23:00/96"

parts:
  rpi-backlight-off:
    plugin: dump
    source: snap/local/scripts
    source-type: local
    organize:
      rpi-backlight-off.sh: opt/rpi-backlight-off/bin/rpi-backlight-off.sh
  rpi-backlight-on:
    plugin: dump
    source: snap/local/scripts
    source-type: local
    organize:
      rpi-backlight-on.sh: opt/rpi-backlight-on/bin/rpi-backlight-on.sh
  