name: rpi-backlight
base: core18
version: '1.0.5'
license: MIT
summary: Backlight switch for Raspberry Pi
description: |
  RPI-Backlight is a very small tool written as bash script to switch the backlight on and off.
  It includes a timer to turn the lights off at 11pm and on at 06am. These parameters are fixed.

  The tool is build for a Raspberry Pi 3 setup running Ubuntu Core. Now it is based on Core18.

  If you like to contribute, please visit my Github repository. 

icon: snap/gui/logo.png
grade: devel
confinement: devmode
architectures:
  - build-on: [armhf, arm64]
    run-on: [armhf, arm64]

apps:
  off:
    command: sh $SNAP/opt/off/bin/backlight-off.sh
    daemon: simple
  on:
    command: sh $SNAP/opt/on/bin/backlight-on.sh
    daemon: simple

parts:
  off:
    plugin: dump
    source: snap/local/scripts
    source-type: local
    organize:
      backlight-off.sh: opt/off/bin/backlight-off.sh
  on:
    plugin: dump
    source: snap/local/scripts
    source-type: local
    organize:
      backlight-on.sh: opt/on/bin/backlight-on.sh
  